### ISSUE TITLE
[Linux] AppImage does not work on KDE desktop.

### ISSUE THREAD

**Issue by CsBigDataHub** [FTCHD/rclone-ui#4]
```
~/AppImages 
❯ ./rclone_ui.appimage      
Gtk-Message: 14:57:05.558: Failed to load module "appmenu-gtk-module": 'gtk_module_display_init': /usr/lib64/gtk-3.0/modules/libwindow-decorations-gtk-module.so: undefined symbol: gtk_module_display_init

(app:17074): Gtk-CRITICAL **: 14:57:05.559: gtk_window_resize: assertion 'width > 0' failed
Gtk-Message: 14:57:05.682: Failed to load module "appmenu-gtk-module": 'gtk_module_display_init': /usr/lib64/gtk-3.0/modules/libwindow-decorations-gtk-module.so: undefined symbol: gtk_module_display_init

** (WebKitWebProcess:17308): WARNING **: 14:57:05.694: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (app:17074): WARNING **: 14:57:30.663: atk-bridge: get_device_events_reply: unknown signature
```

I think, we have 2 options here,
1. Support KDE in AppImage.
2. Flatpak

**Comment by wvpianoman** [comment]
Same error for me

╰─ ❯ ./rclone_ui.appimage
Gtk-Message: 21:23:17.274: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:23:17.276: Failed to load module "appmenu-gtk-module"

(app:53658): Gtk-CRITICAL **: 21:23:17.377: gtk_window_resize: assertion 'width > 0' failed
Gtk-Message: 21:23:17.595: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:23:17.597: Failed to load module "appmenu-gtk-module"

** (WebKitWebProcess:53762): WARNING **: 21:23:17.661: Error loading the injected bundle (././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so): ././/lib/x86_64-linux-gnu/webkit2gtk-4.1/injected-bundle/libwebkit2gtkinjectedbundle.so: cannot open shared object file: No such file or directory
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (app:53658): WARNING **: 21:23:42.559: atk-bridge: get_device_events_reply: unknown signature

I am on BigLinux (based on Manjaro) KDE Plasma 6.2.5 on X11.

**Comment by FTCHD** [comment]
I'm afraid the linux binaries produced by tauri only support Gnome (GTK).

paging @lucasfernog to confirm and hopefully share a solution (if there is any atm).

this could also just be an isolated issue with the menubar/tray, i'm not daily driving linux to know if there's a package you can install to fix this on KDE. the crash is probably happening due to the tray icon (not finding the libs to display it).

**Comment by ChetanKoneru** [comment]
> I'm afraid the linux binaries produced by tauri only support Gnome (GTK).

Is it possible to release `Flatpak` then? Folks can have gtk binaries sandboxed there.

**Comment by FTCHD** [comment]
have you tried [installing the `.deb` version on KDE](https://old.reddit.com/r/kde/comments/1bowu66/how_do_i_install_deb_files_on_kde_neon_i_want_to/kwrv7q2/)?

if you're in a hurry you could follow [these steps](https://v2.tauri.app/distribute/flatpak/) to run it locally as if it were downloaded from flathub. does that work?

**Comment by ChetanKoneru** [comment]
I am on arch linux. Yes let me try to build the flatpack myself. will keep you posted.

**Comment by FTCHD** [comment]
making progress on this, should have something to share soon.

**Comment by FTCHD** [comment]
i've added a `.flatpak` version to the latest release. let me know if this works for you @CsBigDataHub 


this is the config i'm using:
```yaml
runtime: org.gnome.Platform
runtime-version: '46'
sdk: org.gnome.Sdk

command: app
finish-args:
  - --socket=wayland # Permission needed to show the window
  - --socket=fallback-x11 # Permission needed to show the window
  - --device=dri # OpenGL, not necessary for all projects
  - --share=ipc
  - --share=network  # Network access
  - --talk-name=org.freedesktop.Notifications  # Desktop Notifications

modules:
  - shared-modules/libayatana-appindicator/libayatana-appindicator-gtk3.json
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/FTCHD/rclone-ui/releases/download/v1.0.3/Rclone.UI_1.0.3_amd64.deb
        sha256: add7cc23df4548682afd75d4f77c08b258b1d9908dfcd3b8bca3ee508a95092d # This is required if you are using a remote source
        only-arches: [x86_64] #This source is only used on x86_64 Computers
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - 'install -Dm755 usr/bin/app /app/bin/app'
      - install -Dm644 usr/share/applications/'Rclone UI.desktop' /app/share/applications/'Rclone UI.desktop'
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/app.png /app/share/icons/hicolor/128x128/apps/'Rclone UI.png'
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/app.png /app/share/icons/hicolor/32x32/apps/'Rclone UI.png'
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/app.png /app/share/icons/hicolor/256x256@2/apps/'Rclone UI.png'
    #   - install -Dm644 com.stray.app.metainfo.xml /app/share/metainfo/com.stray.app.rosary.metainfo.xml
      - install -Dm644 usr/lib/'Rclone UI'/icons/favicon/icon.png /app/lib/'Rclone UI'/icons/favicon/icon.png
```

should work with `flatpak install`, no desktop icon for now.
